spring.application.name=ecommerce

# Dirección de la base de datos.
# jdbc:mysql:// → protocolo para conectarse a MySQL desde Java.
# localhost → el servidor está en nuestra propia máquina.
# 3306 → puerto por defecto de MySQL.
# techlabdb → nombre de la base que creamos a mano antes de levantar la app.

spring.datasource.url=jdbc:mysql://localhost:3306/techlabdb


####### Usuario root y la contraseña de MySQL Workbench no la envio en esta instancia #######
spring.datasource.username=root
spring.datasource.password=
######################################################


# Driver: el "traductor" que permite que Java hable con MySQL.
# Spring lo usa internamente para enviar y recibir datos de la base.
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ---------------------------------------------------------------
# Configuración de JPA e Hibernate
# ---------------------------------------------------------------
# update → compara nuestras entidades con la base y crea o ajusta las tablas si hace falta. 
spring.jpa.hibernate.ddl-auto=update
# Muestra en la consola el SQL que Hibernate genera por detrás.
spring.jpa.show-sql=true
# hibernate.format_sql → true: acomoda el SQL de la consola con saltos de línea e indentación, 
spring.jpa.properties.hibernate.format_sql=true
# hibernate.dialect → clase de Hibernate traduce las operaciones de JPA a SQL compatible con MySQL.
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect